#+title: Cubical Sets
#+author: James leslie
#+options: h:2 num:t tex:t
#+STARTUP: latexpreview inlineimages hideblocks
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../CSS/JLab.css" /> <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
* Idea
:PROPERTIES:
:ID:       61570dd9-98c5-4d04-9455-0ac3f0146d07
:END:
Cubical sets can be thought of as geometric spaces that can be probed by \(n\)-dimensional cubes. In this respect, they are similar in to simplicial sets, which can be studied with higher dimensional triangles. A difference between the two ideas is that there are many different flavours of cubical sets. They all take the form as presheaves on a box category, but the there are different box categories that one can consider. We will discuss several examples below.

* Definitions
The naming scheme used to differentiate the following box categories is not conventional (I have not seen adjective "standard" used anywhere but here).
** The standard cube category

There are different ways to present the definition of the standard box category, which is the box category with only face and degeneracy maps. The first is the one on [[https://ncatlab.org/nlab/show/category+of+cubes#variants][nLab's Category of Cubes]] page:

#+BEGIN_definition
We define a category \(\square_{\leq 1}\) to be the category freely generated by the following data:
- Objects: Two objects \(I^0\) and \(I^1\);
- Morphisms:
  + Exactly two morphisms \(i_0, i_1 : I^1 \rightarrow I^1\);
  + Exactly one arrow \(p:I^1 \rightarrow I^0\);
  + No non-identity arrows \(I^0 \rightarrow I^0\);
  + Exactly two non-identity arrows \(I^1 \rightarrow I^1\), being \(i_0 \circ p\) and \(i_1 \circ p\).

The /standard box category/, \(\square\), is the free monoidal category on \(\square_{\leq 1}\) with \(I^0\) as the unit.
#+END_definition

An alternative but more concrete definition is given in Definition 1.2 [[[https://arxiv.org/pdf/2005.04853.pdf][DHLS20]]], which also gives the cubical identities (we shift the index on \(\sigma\) to match the simplicial identities used in Cisinski's Homotopical Algebra for simplicial sets).
 
#+BEGIN_definition
The /standard box category/, \(\square\), is defined by the following data:
- Objects: Posets \([1]^n := \{0 < 1\}^n\), for all \(n \in \mathbb{N}\);
- Morphisms:
  + Face maps: \(\partial^n_{i,\epsilon} : [1]^{n-1} \rightarrow [1]^n\) for all \(1 \leq i \leq n\) and \(\epsilon = 0,1\) defined by
    \[\partial^n_{i, \epsilon}(x_1, \ldots, x_{n-1}) = (x_1, x_2, \ldots, x_{i-1}, \epsilon, x_i, \ldots, x_{n-1});\]
  + Degeneracy maps: \(\sigma^n_i:[1]^{n+1} \rightarrow [1]^{n}\) for \(1 \leq i \leq n+1\), given by:
    \[\sigma^n_i(x_1, \ldots, x_{n+1}) = (x_1, \ldots, x_{i-1}, x_{i+1}, \ldots, x_{n+1}).\]
#+END_definition

#+BEGIN_proposition
The face and degeneracy maps satisfy the following /cubical identities/:
1) \(\partial_{j, \epsilon'} \circ \partial_{i, \epsilon} = \partial_{i+1, \epsilon} \circ \partial_{j, \epsilon'}\) for \(j \leq i\);
2) \(\sigma_i \circ \sigma_j = \sigma_j \sigma_{i+1}\) for \(j \leq i\);
3) \(\sigma_j \circ \partial_{i, \epsilon} = \begin{cases} \partial_{i-1, \epsilon} \circ \sigma_j & \text{for } j < i; \\ \operatorname{id} & \text{for } j=i; \\ \partial_{i, \epsilon} \circ \sigma_{j-1} & \text{for } j > i; \end{cases}\).
#+END_proposition

#+BEGIN_proof
We prove this by direct computation.
1) A simple computation shows that both \(\partial^n_{j, \epsilon'} \circ \partial^{n-1}_{i, \epsilon} (x_1, \ldots, x_{n-2})\) and \(\partial^n_{i+1, \epsilon} \circ \partial^{n-1}_{j, \epsilon'} (x_1, \ldots, x_{n-2})\) are equal to
   \[(x_1, \ldots, x_{j-1}, \epsilon', x_{j+1}, \ldots, x_{i-1}, \epsilon, x_{i+1}, \ldots, x_{n-2}) \in [1]^n.\]
2) Likewise, it is easy to show that both \(\sigma^n_i \circ \sigma^{n+1}_j (x_1, \ldots, x_{n+2})\) and \(\sigma^n_j \sigma^{n+1}_{i+1} (x_1, \ldots, x_{n+2})\) are equal to
   \[(x_1, \ldots, x_{j-1}, x_{j+1}, \ldots, x_i, x_{i+2}, \ldots, x_{n+2}) \in [1]^n. \]
3) Computing \(\sigma^n_j \circ \partial^{n+1}_{i, \epsilon} (x_1, \ldots, x_n)\) in the case where \(j < i\) results in \((x_1, \ldots, x_{j-1}, x_{j+1}, \ldots, \epsilon, x_i, \ldots, x_n)\), which is the same as removing the \(j\)-th term and adding \(\epsilon\) into position \(i-1\). That is, it's the same as applying \(\partial^n_{i-1} \circ \sigma^{n-1}_j\). When \(i=j\), we are adding an element in position \(i\), then removing it again, resulting in the identity map. When \(j > i\), we get \((x_1, \ldots, x_{i-1}, \epsilon, x_i, \ldots, x_{j-2}, x_j, \ldots, x_n)\), which is the same as first removing \(x_j\) and adding \(\epsilon\) in position \(i\). That is to say, this is equal to \(\partial^n_{i, \epsilon} \circ \sigma^{n-1}_{j-1}\), as required.
#+END_proof

#+BEGIN_proposition
The two \(\square\) categories are equivalent.
#+END_proposition

#+BEGIN_proof
We define a functor from the first box category to the second in the following way:
- \(I^0 \mapsto [1]^0\);
- \(I^1 \mapsto [1]^1\);
- \(I^{1 \otimes n} \mapsto [1]^n\);
- \(i_\epsilon \mapsto \partial^1_{1, \epsilon}\);
- \(p \mapsto \sigma^0_1\);
- \(I^{1 \otimes n} \otimes i_\epsilon \otimes I^{1 \otimes m} \mapsto \partial^{n+m+1}_{n+1, \epsilon}\);
- \(I^{1 \otimes n} \otimes p \otimes I^{1 \otimes m} \mapsto \sigma^{n+m}_{n+1}\).

This functor is well defined and the conditions on \(\square_{\leq 1}\) agree with the cubical identities. This functor is clearly fully faithful and is surjective on objects, hence the two \(\square\) categories are equivalent.
#+END_proof

As a result of this proposition, we will use the latter terminology for talking about the different  flavours of box categories. 

** Connections
Another common variety of box category is the standard box category plus connections. These connections are another form of degeneracy and are specified as follows.

#+BEGIN_definition
The standard box category with connections, \(\square_{\text{con}}\), is the category generated by the standard box category plus the following maps:
- negative connections \(\gamma^n_{i, 0} : [1]^{n+1} \rightarrow [1]^n\) with \(1 \leq i \leq n\), defined by
  \[\gamma^n_{i,0}(x_1, \ldots, x_{n+1}) = (x_1, \ldots, x_{i-1}, \min(x_i, x_{i+1}), x_{i+2}, \ldots, x_{n+1}.\]
- positive connections \(\gamma^n_{i, 1} : [1]^{n+1} \rightarrow [1]^n\) with \(1 \leq i \leq n\), defined by
  \[\gamma^n_{i,0}(x_1, \ldots, x_{n+1}) = (x_1, \ldots, x_{i-1}, \max(x_i, x_{i+1}), x_{i+2}, \ldots, x_{n+1}.\]

#+END_definition

This category obeys the original cubical identities, but also some involving the newly added connections. These can be found in Definition 1.2 [[[https://arxiv.org/pdf/2005.04853.pdf][DHLS20]]].

** TODO Diagonals
Makes the category cartesian - Monoidal product is now cartesian product. add maps in from \([1]^n \rightarrow [1]^{2n}\) sending (x,)
** TODO Symmetries
Is this the involution?
* TODO De Morgan algebra 
* References
- [[https://ncatlab.org/nlab/show/category+of+cubes#variants][Category of Cubes]] - nLab
- [[https://arxiv.org/abs/2005.04853][Cubical Models of \((\infty,1)\)-Categories]] - Doherty, Kapulkin, Lindsey and Sattler
